### ISSUE TITLE
configure: error: please install libpipewire-0.3-dev or pipewire-devel

### ISSUE THREAD

**Issue by chart41** [neutrinolabs/pipewire-module-xrdp#5]
Ubuntu 22.04
```
./configure

checking for libpipewire-0.3 >= 0.3.58... no
configure: error: please install libpipewire-0.3-dev or pipewire-devel
```

But it has 0.3.48 only =(

Could you fix it, or can I just remove this line checking maybe?

**Comment by elboulangero** [comment]
Check this commit: https://github.com/neutrinolabs/pipewire-module-xrdp/commit/95334f3ecdc028edef4351dd6c447cc995c30324

This is when the check for version `0.3.58` was added. So I suppose it's a hard requirement to have at least this version?

**Comment by metalefty** [comment]
I don't remember why it requires 0.3.58 at least but I guess there's no strong reason.

If someone makes efforts to modify the code to make the module compatible with pipewire 0.3.48 or confirm that it works with 0.3.48, we're happy to accept contributions and relax dependencies.

**Comment by Hiero32** [comment]
This module uses pipewire APIs which are not supported before 0.3.58.
It is hard to support 0.3.48.

@chart41
Default sound server in Ubuntu 22.04 is PulseAudio.
Have you switched sound server to pipewire ?

**Comment by chart41** [comment]
> @chart41 Default sound server in Ubuntu 22.04 is PulseAudio. Have you switched sound server to pipewire ?

How to do it?

**Comment by metalefty** [comment]
@chart41 

What @Hiero32  meant is you should use PulseAudio module instead if you haven't intentionally switched, not you should switch to pipewire. So you don't need to know how to switch.

This module is only needed if you have switched the default sound server to pipewire (but it requires 0.3.58 at least). If you don't know how to do that, I assume you haven't switched to pipewire and  you're using PulseAudio so I would you should use PulseAudio module instead.

**Comment by metalefty** [comment]
Closing this as WONTFIX. This module uses pipewire APIs which are not supported before 0.3.58 and there's no plan to support older versions.
